sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm run cover
  - npm run coverage:check
  - npm run build
after_success:
  - npm run coverage:report
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
